import { NextResponse } from "next/server";
import fs from "node:fs/promises";
import path from "node:path";
import { prisma } from "@/lib/db";
import { authorizeApi } from "@/lib/api-auth";
import { writeAudit } from "@/lib/audit";
const ROOT = path.join(process.cwd(), "storage", "employee-files");
export async function GET(request, { params }) { const { error } = await authorizeApi("OPS_EMPLOYEE_SENSITIVE_READ"); if (error) return error; const { id, documentId } = await params; const doc = await prisma.employeeDocument.findFirst({ where: { id: documentId, employeeId: id } }); if (!doc || doc.status === "REMOVED") return NextResponse.json({ success: false, error: "File not found" }, { status: 404 }); try { const data = await fs.readFile(path.join(ROOT, doc.storageKey)); const disposition = new URL(request.url).searchParams.has("download") ? "attachment" : "inline"; return new NextResponse(data, { headers: { "content-type": doc.mimeType, "content-disposition": `${disposition}; filename="${doc.displayName.replace(/\"/g, "")}"`, "cache-control": "private, no-store", "x-content-type-options": "nosniff" } }); } catch { return NextResponse.json({ success: false, error: "Stored file is unavailable" }, { status: 404 }); } }
export async function DELETE(_request, { params }) { const { user, error } = await authorizeApi("OPS_EMPLOYEE_MANAGE"); if (error) return error; const { id, documentId } = await params; const doc = await prisma.employeeDocument.findFirst({ where: { id: documentId, employeeId: id }, include: { employee: true } }); if (!doc) return NextResponse.json({ success: false, error: "File not found" }, { status: 404 }); await prisma.employeeDocument.update({ where: { id: doc.id }, data: { status: "REMOVED" } }); await writeAudit({ action: "OPS_EMPLOYEE_DOCUMENT_REMOVED", user, summary: `Removed ${doc.documentType} for ${doc.employee.name}`, metadata: { employeeId: id, documentId } }); return NextResponse.json({ success: true }); }
