"use client";
import { useMemo, useState } from "react";
import { annualEmployeeInsights } from "@/lib/operations/employee-intelligence";

const copy = {
  en: { title: "Manager AI Assistant", period: "Report year", summary: "AI Yearly Brief", risks: "Risk signals", strengths: "Strengths", plan: "Development plan", evidence: "Evidence", limited: "This assistant uses only recorded Employee 360 data. It creates a draft for manager review; it does not make employment decisions.", FOLLOW_UP: "Follow up", TRAINING: "Training required", READY_FOR_MORE: "Ready for more responsibility", STABLE: "Stable in role" },
  ar: { title: "مساعد المدير الذكي", period: "سنة التقرير", summary: "ملخص السنة الذكي", risks: "تنبيهات المخاطر", strengths: "نقاط القوة", plan: "خطة التطوير", evidence: "الدليل", limited: "المساعد يعتمد فقط على بيانات Employee 360 المسجلة. النتيجة مسودة لمراجعة المدير وليست قرارًا وظيفيًا تلقائيًا.", FOLLOW_UP: "يحتاج متابعة", TRAINING: "يحتاج تدريب", READY_FOR_MORE: "جاهز لمسؤولية إضافية", STABLE: "مستقر في دوره" },
};

export default function EmployeeIntelligence({ employee, language = "en" }) {
  const [year, setYear] = useState(String(new Date().getFullYear())); const [question, setQuestion] = useState("summary"); const text = copy[language];
  const insight = useMemo(() => annualEmployeeInsights(employee, year), [employee, year]);
  const brief = insight.performanceScore === null && insight.attendanceRate === null ? (language === "ar" ? "البيانات المسجلة غير كافية لإصدار ملخص سنوي." : "Recorded data is not sufficient for a yearly brief.") : (language === "ar" ? `خلال ${year}، متوسط الأداء ${insight.performanceScore ?? "غير متاح"}${insight.performanceScore !== null ? "%" : ""}، والالتزام بالحضور ${insight.attendanceRate ?? "غير متاح"}${insight.attendanceRate !== null ? "%" : ""}. التوصية الحالية: ${text[insight.recommendation]}.` : `During ${year}, recorded performance averages ${insight.performanceScore ?? "not available"}${insight.performanceScore !== null ? "%" : ""} and attendance is ${insight.attendanceRate ?? "not available"}${insight.attendanceRate !== null ? "%" : ""}. Current recommendation: ${text[insight.recommendation]}.`);
  return <section className="employee-intelligence" dir={language === "ar" ? "rtl" : "ltr"}><header><div><h3>{text.title}</h3><p>{text.limited}</p></div><label>{text.period}<select aria-label={text.period} value={year} onChange={(event) => setYear(event.target.value)}>{[0, 1, 2].map((offset) => <option key={offset} value={new Date().getFullYear() - offset}>{new Date().getFullYear() - offset}</option>)}</select></label></header><div className="employee-ai-questions">{["summary", "promotion", "training", "attendance"].map((item) => <button className={question === item ? "active" : ""} onClick={() => setQuestion(item)} key={item}>{item === "summary" ? text.summary : item === "promotion" ? (language === "ar" ? "هل هو جاهز؟" : "Is the employee ready?") : item === "training" ? (language === "ar" ? "ما التدريب المطلوب؟" : "What training is needed?") : (language === "ar" ? "ملخص الحضور" : "Attendance summary")}</button>)}</div><article className="employee-ai-brief"><b>{question === "summary" ? text.summary : question === "promotion" ? text.plan : question === "training" ? text.plan : text.evidence}</b><p>{question === "attendance" ? (language === "ar" ? `الحضور: ${insight.present}/${insight.expected || "—"}، التأخير: ${insight.late}، الغياب: ${insight.absences}، الخروج المبكر: ${insight.earlyLeave}.` : `Attendance: ${insight.present}/${insight.expected || "—"}; late: ${insight.late}; absent: ${insight.absences}; early leave: ${insight.earlyLeave}.`) : question === "training" ? (insight.missingQualifications.length ? insight.missingQualifications.map((item) => item.label).join(", ") : (language === "ar" ? "لا توجد مؤهلات تشغيل ناقصة في السجل." : "No missing operational qualifications are recorded.")) : brief}</p></article><div className="grid two"><article><h4>{text.risks}</h4>{insight.signals.length ? insight.signals.map((item) => <div className={`employee-ai-signal ${item.severity.toLowerCase()}`} key={item.code}><b>{item.code}</b><span>{item.evidence}</span></div>) : <p className="muted">{language === "ar" ? "لا توجد مخاطر مبنية على البيانات المسجلة." : "No data-backed risk signals."}</p>}</article><article><h4>{text.strengths}</h4>{insight.strengths.length ? insight.strengths.map((item) => <div className="employee-ai-strength" key={item}>{item}</div>) : <p className="muted">{language === "ar" ? "لا توجد أدلة كافية لإظهار نقاط قوة." : "No recorded evidence yet."}</p>}</article></div><footer><b>{text.plan}:</b> {text[insight.recommendation]}</footer></section>;
}
