"use client";
import { useMemo, useState } from "react";
import EmployeeIntelligence from "./EmployeeIntelligence";
import EmployeeAnnualFile from "./EmployeeAnnualFile";

const tabs = ["Overview", "Personal", "Employment", "Documents", "Schedule & Attendance", "Leaves & Balances", "Performance", "Guest Feedback", "Guidance & Penalties", "Training & Qualifications", "Recognition", "Timeline", "Files", "Manager AI Assistant"];
const activeTabs = tabs;
const formats = { STANDARD: ["Overview", "Employment", "Schedule & Attendance"], MANAGEMENT: ["Overview", "Employment", "Schedule & Attendance", "Leaves & Balances", "Performance", "Guest Feedback", "Guidance & Penalties", "Training & Qualifications", "Recognition", "Timeline"], FULL_RESTRICTED: ["Overview", "Personal", "Employment", "Documents", "Schedule & Attendance", "Leaves & Balances", "Performance", "Guest Feedback", "Guidance & Penalties", "Training & Qualifications", "Recognition", "Timeline", "Files"] };
const date = (value) => value ? new Date(value).toLocaleDateString() : "—";
const initials = (name) => name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("");

function Table({ rows = [], columns }) {
  return <div className="record-table-scroll"><table className="record-line-table"><thead><tr>{columns.map((column) => <th key={column.label}>{column.label}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={row.id || index}>{columns.map((column) => <td key={column.label}>{column.value(row) ?? "—"}</td>)}</tr>) : <tr><td colSpan={columns.length}>No records yet</td></tr>}</tbody></table></div>;
}

function Notice({ children }) { return <div className="muted employee360-empty">{children}</div>; }

export default function Employee360View({ employee, onReload }) {
  const [tab, setTab] = useState("Overview");
  const [mode, setMode] = useState("STANDARD");
  const [custom, setCustom] = useState(formats.STANDARD);
  const [fileOpen, setFileOpen] = useState(false);
  const [fileLanguage, setFileLanguage] = useState("en");
  const [fileYear, setFileYear] = useState(String(new Date().getFullYear()));
  const [fileEndDate, setFileEndDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [personal, setPersonal] = useState(() => ({ dateOfBirth: employee.dateOfBirth?.slice(0, 10) || "", phone: employee.phone || "", address: employee.address || "", nationalId: employee.nationalId || "", emergencyName: employee.emergencyName || "", emergencyPhone: employee.emergencyPhone || "", emergencyRelation: employee.emergencyRelation || "", personalNotes: employee.personalNotes || "" }));
  const photo = employee.photo ? `/api/operations/employees/${employee.id}/documents/${employee.photo.id}` : null;
  const selectedSections = mode === "CUSTOM" ? custom : formats[mode];
  const reload = () => onReload?.();
  const post = async (body) => { const response = await fetch(`/api/operations/employees/${employee.id}/360`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) alert((await response.json()).error || "Could not save"); else reload(); };
  const savePersonal = async () => { const response = await fetch(`/api/operations/employees/${employee.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(personal) }); if (!response.ok) alert((await response.json()).error || "Could not save"); else reload(); };
  const printFile = () => { document.body.dataset.employeeFilePrint = "true"; window.print(); window.setTimeout(() => delete document.body.dataset.employeeFilePrint, 500); };
  const content = (name, printable = false) => <Section name={name} employee={employee} personal={personal} setPersonal={setPersonal} savePersonal={savePersonal} post={post} reload={reload} printable={printable} />;

  return <section className="employee360">
    <header className="panel employee360-head">
      <div className="employee360-photo">{photo ? <img src={photo} alt={employee.name} /> : <b>{initials(employee.name)}</b>}</div>
      <div className="employee360-identity"><span className="employee360-eyebrow">EMPLOYEE 360</span><h2>{employee.name}</h2><p>{employee.hrisNumber || employee.localEmployeeCode || "No employee code"} · {employee.jobTitle || "No job title"}</p><div className="employee360-badges"><b>{employee.employmentStatus}</b><span>{employee.employmentType}</span><span>{employee.department || "No department"}</span></div></div>
    </header>
    <section className="panel employee360-tools"><div><b>Employee file</b><span>Choose the sections and period, then open the complete file.</span></div><div className="employee-file-controls"><select aria-label="Employee file format" value={mode} onChange={(event) => setMode(event.target.value)}><option value="STANDARD">Standard file</option><option value="MANAGEMENT">Management file</option><option value="FULL_RESTRICTED">Full restricted file</option><option value="CUSTOM">Custom sections</option></select><select aria-label="Employee file language" value={fileLanguage} onChange={(event) => setFileLanguage(event.target.value)}><option value="en">English</option><option value="ar">العربية</option></select><select aria-label="Employee file year" value={fileYear} onChange={(event) => { const year = event.target.value; setFileYear(year); setFileEndDate(Number(year) === new Date().getFullYear() ? new Date().toISOString().slice(0, 10) : `${year}-12-31`); }}>{[0, 1, 2].map((offset) => <option key={offset} value={new Date().getFullYear() - offset}>{new Date().getFullYear() - offset}</option>)}</select><label>To <input aria-label="Employee file end date" type="date" min={`${fileYear}-01-01`} max={`${fileYear}-12-31`} value={fileEndDate} onChange={(event) => setFileEndDate(event.target.value)} /></label><button onClick={() => setFileOpen(true)}>Open complete file</button></div></section>
    {mode === "CUSTOM" && <div className="panel employee360-custom">{activeTabs.map((item) => <label key={item}><input type="checkbox" checked={custom.includes(item)} onChange={() => setCustom((current) => current.includes(item) ? current.filter((x) => x !== item) : [...current, item])} /> {item}</label>)}</div>}
    <div className="employee360-body">
      <nav className="panel employee360-tabs" aria-label="Employee file sections">{activeTabs.map((item, index) => <button type="button" className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}><small>{String(index + 1).padStart(2, "0")}</small><span>{item}</span></button>)}</nav>
      <section className="panel employee360-content">{tab === "Manager AI Assistant" ? <EmployeeIntelligence employee={employee} language={fileLanguage} /> : content(tab)}</section>
    </div>
    {fileOpen && <div className="employee-file-preview"><div className="employee-file-preview-actions"><b>{fileLanguage === "ar" ? "ملف الموظف السنوي" : "Annual Employee File"} · {fileYear}-01-01 → {fileEndDate}</b><button onClick={printFile}>Print / Save as PDF</button><button onClick={() => setFileOpen(false)}>Close preview</button></div><article className="employee-file-sheet"><EmployeeAnnualFile employee={employee} year={fileYear} endDate={fileEndDate} language={fileLanguage} />{selectedSections.length ? selectedSections.map((item) => <div className="employee-file-section" key={item}>{content(item, true)}</div>) : <Notice>Select at least one section.</Notice>}<p className="employee-file-note">Original attachment merging is explicitly deferred. Files are listed as protected records and are not embedded in this PDF preview.</p></article></div>}
  </section>;
}

function Section({ name, employee, personal, setPersonal, savePersonal, post, reload, printable }) {
  const docs = employee.documents || [];
  if (name === "Overview") return <div className="employee360-section"><h3>Overview</h3><div className="grid three operations-facts">{[["Branch", employee.branch], ["Department", employee.department], ["Hire date", date(employee.hireDate)], ["Attendance", employee.attendanceRecords?.length], ["Appraisals", employee.monthlyAppraisals?.length], ["Recognition", employee.recognition?.length]].map(([label, value]) => <div key={label}><span>{label}</span><b>{value || "—"}</b></div>)}</div></div>;
  if (name === "Personal") return <div className="employee360-section"><h3>Personal</h3><div className="employee360-form">{[["dateOfBirth", "Date of birth", "date"], ["phone", "Phone"], ["address", "Address"], ["nationalId", "National ID"], ["emergencyName", "Emergency contact"], ["emergencyPhone", "Emergency phone"], ["emergencyRelation", "Relationship"], ["personalNotes", "Confidential notes"]].map(([field, label, type]) => <label key={field}>{label}<input type={type || "text"} value={personal[field]} onChange={(event) => setPersonal({ ...personal, [field]: event.target.value })} disabled={printable} /></label>)}{!printable && <button onClick={savePersonal}>Save personal details</button>}</div></div>;
  if (name === "Employment") return <div className="employee360-section"><h3>Employment history</h3><Table rows={(employee.employmentPeriods || []).flatMap((period) => period.assignments || [])} columns={[{ label: "Position", value: (x) => x.positionName }, { label: "Code", value: (x) => x.jobCode }, { label: "From", value: (x) => date(x.effectiveFrom) }, { label: "To", value: (x) => date(x.effectiveTo) }, { label: "Reason", value: (x) => x.changeReason }]} />{!printable && <EmploymentForm onSave={post} />}<Table rows={employee.employmentEvents} columns={[{ label: "Event", value: (x) => x.eventType }, { label: "Effective", value: (x) => date(x.effectiveDate) }, { label: "Before", value: (x) => x.previousValue }, { label: "After", value: (x) => x.newValue }, { label: "Reason", value: (x) => x.reason }]} /></div>;
  if (name === "Documents") return <div className="employee360-section"><h3>Documents</h3>{!printable && <DocumentUpload employee={employee} reload={reload} />}<Table rows={docs} columns={[{ label: "Type", value: (x) => x.documentType }, { label: "File", value: (x) => x.displayName }, { label: "Issue", value: (x) => date(x.issueDate) }, { label: "Expiry", value: (x) => date(x.expiryDate) }, { label: "Status", value: (x) => x.expiryStatus || x.status }, { label: "Notes", value: (x) => x.notes }]} />{!printable && docs.filter((x) => x.status === "ACTIVE").map((x) => <div className="employee-doc-actions" key={x.id}><a href={`/api/operations/employees/${employee.id}/documents/${x.id}`} target="_blank">View {x.displayName}</a><a href={`/api/operations/employees/${employee.id}/documents/${x.id}?download=1`}>Download</a><button onClick={async () => { if (window.confirm(`Remove ${x.displayName}?`)) { await fetch(`/api/operations/employees/${employee.id}/documents/${x.id}`, { method: "DELETE" }); reload(); } }}>Remove</button></div>)}</div>;
  if (name === "Schedule & Attendance") return <div className="employee360-section"><h3>Schedule & Attendance</h3><Table rows={employee.scheduleAssignments} columns={[{ label: "Date", value: (x) => x.workDate }, { label: "Code", value: (x) => x.code }, { label: "Shift", value: (x) => x.shiftCode }, { label: "Schedule", value: (x) => x.schedule?.status }]} /><Table rows={employee.attendanceRecords} columns={[{ label: "Date", value: (x) => x.attendanceDay?.workDate }, { label: "Expected", value: (x) => x.expectedCode }, { label: "In", value: (x) => x.actualIn }, { label: "Out", value: (x) => x.actualOut }, { label: "Status", value: (x) => x.status }]} /></div>;
  if (name === "Leaves & Balances") return <div className="employee360-section"><h3>Leaves & Balances</h3><Table rows={employee.leaveAccounts} columns={[{ label: "Leave type", value: (x) => x.leaveType }, { label: "Year", value: (x) => x.leaveYear }, { label: "Balance", value: (x) => (x.transactions || []).reduce((sum, item) => sum + item.amount, 0) }]} /><Table rows={employee.overtimeTransactions} columns={[{ label: "Date", value: (x) => date(x.transactionDate) }, { label: "Minutes", value: (x) => x.minutes }, { label: "Type", value: (x) => x.transactionType }, { label: "Reason", value: (x) => x.reason }]} /></div>;
  if (name === "Performance") return <div className="employee360-section"><h3>Performance</h3><Table rows={employee.dailyEvaluations} columns={[{ label: "Date", value: (x) => x.dailyEvaluationDay?.evaluationDate }, { label: "Score", value: (x) => `${x.finalScore}/${x.maxScore}` }, { label: "Status", value: (x) => x.status }, { label: "Supervisor note", value: (x) => x.supervisorNote }]} /><Table rows={employee.monthlyAppraisals} columns={[{ label: "Period", value: (x) => `${x.year}/${x.month}` }, { label: "Score", value: (x) => x.totalScore }, { label: "Status", value: (x) => x.status }, { label: "Version", value: (x) => x.version }]} /></div>;
  if (name === "Guest Feedback") return <div className="employee360-section"><h3>Guest Feedback</h3>{!printable && <GuestFeedbackForm onSave={post} />}<Table rows={employee.guestFeedback} columns={[{ label: "Date", value: (x) => date(x.feedbackDate) }, { label: "Source", value: (x) => x.source }, { label: "Rating", value: (x) => x.rating ? `${x.rating}/5` : "—" }, { label: "Category", value: (x) => x.category }, { label: "Feedback", value: (x) => x.comment }, { label: "Follow-up", value: (x) => x.followUp }, { label: "Status", value: (x) => x.status }]} /></div>;
  if (name === "Guidance & Penalties") return <div className="employee360-section"><h3>Guidance & Penalties</h3>{!printable && <GuidanceForm onSave={post} />}<Table rows={employee.guidanceRecords} columns={[{ label: "Date", value: (x) => date(x.recordDate) }, { label: "Type", value: (x) => x.recordType }, { label: "Record", value: (x) => x.title }, { label: "Details", value: (x) => x.details }, { label: "Points", value: (x) => x.points }, { label: "Action", value: (x) => x.actionTaken }, { label: "Follow-up", value: (x) => date(x.followUpDate) }, { label: "Status", value: (x) => x.status }]} /></div>;
  if (name === "Training & Qualifications") return <div className="employee360-section"><h3>Training & Qualifications</h3>{!printable && <><TrainingForm onSave={post} /><QualificationForm positions={employee.operationalPositions} onSave={post} /></>}<Table rows={employee.trainingRecords} columns={[{ label: "Training", value: (x) => x.name }, { label: "Category", value: (x) => x.category }, { label: "Completed", value: (x) => date(x.completedDate) }, { label: "Expiry", value: (x) => date(x.expiryDate) }, { label: "Status", value: (x) => x.status }, { label: "Provider", value: (x) => x.provider }]} /><Table rows={employee.qualifications} columns={[{ label: "Operational position", value: (x) => x.position?.label }, { label: "Status", value: (x) => x.status }, { label: "Effective", value: (x) => date(x.effectiveDate) }, { label: "Expiry", value: (x) => date(x.expiryDate) }, { label: "Notes", value: (x) => x.notes }]} /></div>;
  if (name === "Recognition") return <div className="employee360-section"><h3>Recognition</h3><Table rows={employee.recognition} columns={[{ label: "Year", value: (x) => x.year }, { label: "Month", value: (x) => x.month }, { label: "Status", value: (x) => x.status }]} /><Table rows={employee.succession} columns={[{ label: "Target role", value: (x) => x.targetRole }, { label: "Readiness", value: (x) => x.readinessStatus }, { label: "Review date", value: (x) => date(x.readinessReviewDate) }]} /></div>;
  if (name === "Timeline") return <div className="employee360-section"><h3>Unified Timeline</h3><Table rows={employee.timeline} columns={[{ label: "Type", value: (x) => x.type }, { label: "Date", value: (x) => date(x.date) }, { label: "Record", value: (x) => x.title }, { label: "Detail", value: (x) => x.detail }]} /></div>;
  if (name === "Files") return <div className="employee360-section"><h3>Files</h3><Table rows={docs} columns={[{ label: "Type", value: (x) => x.documentType }, { label: "Name", value: (x) => x.displayName }, { label: "Format", value: (x) => x.mimeType }, { label: "Size", value: (x) => `${Math.ceil(x.sizeBytes / 1024)} KB` }, { label: "Uploaded", value: (x) => date(x.uploadedAt) }, { label: "Status", value: (x) => x.status }]} /></div>;
  return <div className="employee360-section"><h3>{name}</h3><Notice>This section is intentionally deferred to a later Employee 360 phase. No data has been invented.</Notice></div>;
}

function EmploymentForm({ onSave }) { const [form, setForm] = useState({ eventType: "POSITION_CHANGE", effectiveDate: new Date().toISOString().slice(0, 10), newValue: "", reason: "", applyCurrent: true }); return <form className="employee360-form" onSubmit={(event) => { event.preventDefault(); onSave({ action: "employmentEvent", ...form }); }}><label>Event type<select aria-label="Employment event type" value={form.eventType} onChange={(e) => setForm({ ...form, eventType: e.target.value })}><option>POSITION_CHANGE</option><option>BRANCH_TRANSFER</option><option>SUPERVISOR_CHANGE</option><option>OTHER</option></select></label><label>Effective date<input type="date" value={form.effectiveDate} onChange={(e) => setForm({ ...form, effectiveDate: e.target.value })} /></label><label>New value<input required value={form.newValue} onChange={(e) => setForm({ ...form, newValue: e.target.value })} /></label><label>Reason<input value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /></label><label><input type="checkbox" checked={form.applyCurrent} onChange={(e) => setForm({ ...form, applyCurrent: e.target.checked })} /> Apply to current employment profile</label><button>Add employment event</button></form>; }
function TrainingForm({ onSave }) { const [form, setForm] = useState({ name: "", category: "", completedDate: "", expiryDate: "", provider: "", status: "COMPLETED", notes: "" }); return <form className="employee360-form" onSubmit={(event) => { event.preventDefault(); onSave({ action: "training", ...form }); }}><label>Training name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Category<input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label>Completed<input type="date" value={form.completedDate} onChange={(e) => setForm({ ...form, completedDate: e.target.value })} /></label><label>Expiry<input type="date" value={form.expiryDate} onChange={(e) => setForm({ ...form, expiryDate: e.target.value })} /></label><label>Provider<input value={form.provider} onChange={(e) => setForm({ ...form, provider: e.target.value })} /></label><label>Status<select aria-label="Record status" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>COMPLETED</option><option>IN_PROGRESS</option><option>EXPIRED</option></select></label><label>Notes<input value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><button>Add training</button></form>; }
function QualificationForm({ positions = [], onSave }) { const [form, setForm] = useState({ operationalPositionId: "", status: "QUALIFIED", effectiveDate: "", expiryDate: "", notes: "" }); return <form className="employee360-form" onSubmit={(event) => { event.preventDefault(); onSave({ action: "qualification", ...form }); }}><label>Operational position<select aria-label="Operational position" required value={form.operationalPositionId} onChange={(e) => setForm({ ...form, operationalPositionId: e.target.value })}><option value="">Select position</option>{positions.map((position) => <option value={position.id} key={position.id}>{position.label}</option>)}</select></label><label>Status<select aria-label="Record status" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>QUALIFIED</option><option>NOT_QUALIFIED</option><option>EXPIRED</option></select></label><label>Effective<input type="date" value={form.effectiveDate} onChange={(e) => setForm({ ...form, effectiveDate: e.target.value })} /></label><label>Expiry<input type="date" value={form.expiryDate} onChange={(e) => setForm({ ...form, expiryDate: e.target.value })} /></label><label>Notes<input value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><button>Save qualification</button></form>; }
function GuestFeedbackForm({ onSave }) { const [form, setForm] = useState({ feedbackDate: new Date().toISOString().slice(0, 10), source: "GUEST", guestName: "", guestPhone: "", rating: "", category: "", comment: "", followUp: "", status: "OPEN" }); return <form className="employee360-form" onSubmit={(event) => { event.preventDefault(); onSave({ action: "guestFeedback", ...form }); }}><label>Date<input type="date" required value={form.feedbackDate} onChange={(e) => setForm({ ...form, feedbackDate: e.target.value })} /></label><label>Source<select aria-label="Feedback source" value={form.source} onChange={(e) => setForm({ ...form, source: e.target.value })}><option>GUEST</option><option>PARENT</option><option>SUPERVISOR</option><option>ONLINE</option></select></label><label>Guest name<input value={form.guestName} onChange={(e) => setForm({ ...form, guestName: e.target.value })} /></label><label>Phone<input value={form.guestPhone} onChange={(e) => setForm({ ...form, guestPhone: e.target.value })} /></label><label>Rating<select aria-label="Feedback rating" value={form.rating} onChange={(e) => setForm({ ...form, rating: e.target.value })}><option value="">No rating</option>{[1,2,3,4,5].map((value) => <option key={value}>{value}</option>)}</select></label><label>Category<input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label>Feedback<textarea aria-label="Feedback comment" required value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })} /></label><label>Follow-up<textarea aria-label="Feedback follow-up" value={form.followUp} onChange={(e) => setForm({ ...form, followUp: e.target.value })} /></label><label>Status<select aria-label="Feedback status" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>OPEN</option><option>RESOLVED</option><option>NO_ACTION</option></select></label><button>Save guest feedback</button></form>; }
function GuidanceForm({ onSave }) { const [form, setForm] = useState({ recordDate: new Date().toISOString().slice(0, 10), recordType: "GUIDANCE", title: "", details: "", points: "", actionTaken: "", followUpDate: "", status: "OPEN" }); return <form className="employee360-form" onSubmit={(event) => { event.preventDefault(); onSave({ action: "guidance", ...form }); }}><label>Date<input type="date" required value={form.recordDate} onChange={(e) => setForm({ ...form, recordDate: e.target.value })} /></label><label>Type<select aria-label="Guidance record type" value={form.recordType} onChange={(e) => setForm({ ...form, recordType: e.target.value })}><option>GUIDANCE</option><option>WARNING</option><option>PENALTY</option><option>COMMENDATION</option></select></label><label>Title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Details<textarea aria-label="Guidance details" value={form.details} onChange={(e) => setForm({ ...form, details: e.target.value })} /></label><label>Points (+/-)<input type="number" step="0.5" value={form.points} onChange={(e) => setForm({ ...form, points: e.target.value })} /></label><label>Action taken<textarea aria-label="Guidance action taken" value={form.actionTaken} onChange={(e) => setForm({ ...form, actionTaken: e.target.value })} /></label><label>Follow-up date<input type="date" value={form.followUpDate} onChange={(e) => setForm({ ...form, followUpDate: e.target.value })} /></label><label>Status<select aria-label="Guidance status" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>OPEN</option><option>CLOSED</option><option>APPEALED</option></select></label><button>Save guidance record</button></form>; }
function DocumentUpload({ employee, reload }) { const [file, setFile] = useState(null); const [busy, setBusy] = useState(false); const [form, setForm] = useState({ documentType: "OTHER", displayName: "", issueDate: "", expiryDate: "", notes: "" }); const upload = async () => { if (!file || busy) return; const targetEmployeeId = employee.id; const data = new FormData(); data.set("file", file); data.set("employeeId", targetEmployeeId); Object.entries(form).forEach(([key, value]) => data.set(key, value)); setBusy(true); try { const response = await fetch(`/api/operations/employees/${targetEmployeeId}/documents`, { method: "POST", body: data }); const payload = await response.json(); if (!response.ok || payload.document?.employeeId !== targetEmployeeId) throw new Error(payload.error || "Upload target verification failed"); setFile(null); setForm((current) => ({ ...current, displayName: "", issueDate: "", expiryDate: "", notes: "" })); reload(); } catch (error) { alert(error.message || "Upload failed"); } finally { setBusy(false); } }; return <div className="employee360-form" data-employee-id={employee.id}><p className="muted">Upload target: <b>{employee.name}</b> · {employee.hrisNumber || employee.localEmployeeCode || employee.id}</p><label>Type<select aria-label="Document type" value={form.documentType} onChange={(e) => setForm({ ...form, documentType: e.target.value })}>{["EMPLOYEE_PHOTO", "NATIONAL_ID_FRONT", "NATIONAL_ID_BACK", "CONTRACT", "CERTIFICATE", "OTHER"].map((type) => <option key={type}>{type}</option>)}</select></label><label>Display name<input value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} /></label><label>Issue date<input type="date" value={form.issueDate} onChange={(e) => setForm({ ...form, issueDate: e.target.value })} /></label><label>Expiry date<input type="date" value={form.expiryDate} onChange={(e) => setForm({ ...form, expiryDate: e.target.value })} /></label><label>Notes<input value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><label>Secure local file<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy} onChange={(e) => setFile(e.target.files?.[0] || null)} /></label><button type="button" disabled={!file || busy} onClick={upload}>{busy ? "Uploading…" : `Upload document for ${employee.name}`}</button></div>; }
